/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    DialogConfirm: typeof import('./src/components/movie/DialogConfirm.vue')['default']
    DialogfORMMovie: typeof import('./src/components/movie/DialogFormMovie.vue')['default']
    DialogFormMovie: typeof import('./src/components/movie/DialogFormMovie.vue')['default']
    DialogInfoMovie: typeof import('./src/components/movie/DialogInfoMovie.vue')['default']
    DialogInfoPokemon: typeof import('./src/components/pokemon/DialogInfoPokemon.vue')['default']
    DialogMovie: typeof import('./src/components/movie/DialogFormMovie.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    HomeMovie: typeof import('./src/components/movie/Movie.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Movie: typeof import('./src/components/movie/Movie.vue')['default']
    Pokemon: typeof import('./src/components/pokemon/Pokemon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
