/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/chooseEnemie/': RouteRecordInfo<'/chooseEnemie/', '/chooseEnemie', Record<never, never>, Record<never, never>>,
    '/chooseEnemie/arena/[id]': RouteRecordInfo<'/chooseEnemie/arena/[id]', '/chooseEnemie/arena/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/movie': RouteRecordInfo<'/movie', '/movie', Record<never, never>, Record<never, never>>,
    '/pokemon': RouteRecordInfo<'/pokemon', '/pokemon', Record<never, never>, Record<never, never>>,
  }
}
